### ISSUE TITLE
Repo Out-of-Date

### ISSUE THREAD

**Issue by mkneierV** [jgillick/LendingClub#17]
It appears Lending Club has updated their API since this repos development. Are there plans to update it? If not, I would be interested in contributing to its development.

**Comment by jgillick** [comment]
Thank you for the heads up. I probably won't have time to update it until August at the earliest (I have another pressing project taking all my time). I'd love any contributions you'd like to make! Thank you.

**Comment by jdfoote** [comment]
FYI, I created a really basic python implementation using the new API at https://github.com/jdfoote/LendingClubInvestor. Any contributions welcome :)

**Comment by jgillick** [comment]
@mkneierV This library doesn't actually use the official LendingClub API. It was written before they released the API publicly, so it uses their unpublished JSON endpoints that I found by inspecting HTTP requests while performing various actions. So the updated API doesn't affect this library. That said, I'd love to move my functions over to their standardized library in the future.

**Comment by jgillick** [comment]
@jdfoote That's really cool, are you still working on it? I've been wanting to port my library over to using the official APIs for awhile but just haven't had time.

**Comment by mkneierV** [comment]
@jgillick that makes sense. I was working on building some predictive models around lending club notes, and ended up updating most of the API calls. You can check it our here if it is useful! 

https://github.com/mkneierV/LendingClubML

**Comment by jdfoote** [comment]
@jgillick I haven't updated it for a while - it works for my needs right now. You are welcome to contribute, or to just use any of the code that you want for your application.

@mkneierV Your project looks super cool. I have been wanting to do some ML on LC data as well, and your project looks like a great start.
